# Numpy Exercises 2

In [1]:
import numpy as np

import matplotlib.pyplot as plt
import random # Thư viện built-in của Python 

**Question 1**

Search for the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as `True`. First time occurrences should be `False` \
Input: `[0 0 3 0 2 4 2 2 2 2]` \
Correct Output: `[False  True False  True False False  True  True  True  True]`

In [2]:
#Init array
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)
#TODO
out = np.full(a.shape[0], True)
unique_positions = np.unique(a, return_index = True)[1]
out[unique_positions] = False
print(f'Correct Output: {out}')

Array:  [0 0 3 0 2 4 2 2 2 2]
Correct Output: [False  True False  True False False  True  True  True  True]


**Question 2**

Return all items in array `a` that not in array `b` \
Input: \
`a` = `[1,2,3,4,5]` \
`b` = `[5,6,7,8,9]` \
Output: \
`[1,2,3,4]`

In [3]:
a = np.random.choice(range(10), 7, replace=False)
b = np.random.choice(range(10), 7, replace=False)
print(a,b)
#TODO
print(np.setdiff1d(a, b))

[5 9 7 2 6 3 4] [0 7 1 8 5 4 3]
[2 6 9]


**Question 3**

Given a vector `a`, build a new vector with 2 consecutive zeros interleaved between each value. \
Input: \
`a` = `[4, 3, 4, 9, 8]` \
Output: \
`[4. 0. 0. 3. 0. 0. 4. 0. 0. 9. 0. 0. 8.]`

In [4]:
a = np.random.randint(1, 10, 5)
#TODO
print(f'Original array: {a}')
new_a = np.zeros(len(a) + (len(a) - 1) * 2)
new_a[::3] = a
print(f'Output: {new_a}')

Original array: [6 4 5 5 4]
Output: [6. 0. 0. 4. 0. 0. 5. 0. 0. 5. 0. 0. 4.]


---
*For the next few questions we will work with `Iris Dataset`*

In [5]:
iris_2d = np.genfromtxt('Data/Iris.csv', delimiter=',', dtype='float', 
                        skip_header=1, usecols=[0,1,2,3])
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

**Question 4**\
Filter the rows of iris_2d that has `petallength` (3rd column) > 1.5 and `sepallength` (1st column) < 5.0

In [6]:
#TODO
iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

**Question 5**\
Add a new text column to `iris_2d`, which based on the petal length (3rd) column, such that if petal length is: \
- `Less than 3` --> 'small'
- `3-5` --> 'medium'
- `>=5` --> 'large'

In [7]:
#TODO
petal_length_bin = np.digitize(iris_2d[:, 2].astype('float'), [0, 3, 5, 10])

label_map = {1 : 'small', 2 : 'medium', 3 : 'large', 4 : np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]
petal_length_cat

['small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'mediu

**Question 6**\
Find the value of second longest `petallength` of species `setosa`

In [8]:
#TODO
iris_2d = np.genfromtxt('Data/Iris.csv', delimiter=',', dtype='object')
setosa = iris_2d[iris_2d[:, 4] == b'Iris-setosa', [2]].astype('float')
np.unique(np.sort(setosa))[-2]

1.7